#!/usr/bin/env python3
"""
Manager Pulse - Proactive oversight system

The Manager runs a background loop that:
- Checks on agent health every minute
- Follows up on stuck missions
- Reports status to user proactively
- Can take initiative to spawn agents or restart failed ones
"""
import threading
import time
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Callable
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class PulseEvent:
    """An event generated by the Manager's pulse"""
    timestamp: datetime
    type: str  # 'health_check', 'mission_update', 'agent_alert', 'status_report'
    severity: str  # 'info', 'warning', 'action_taken'
    message: str
    agent_id: Optional[str] = None
    mission_id: Optional[str] = None
    suggested_action: Optional[str] = None


class ManagerPulse:
    """
    Proactive Manager oversight system
    
    Runs in background and monitors the Workspace, generating
    events and taking action when needed.
    """
    
    # Check intervals (seconds)
    HEALTH_CHECK_INTERVAL = 60      # Every minute
    MISSION_CHECK_INTERVAL = 120    # Every 2 minutes  
    STATUS_REPORT_INTERVAL = 300    # Every 5 minutes
    
    # Thresholds
    STUCK_THRESHOLD_MINUTES = 5
    SILENT_THRESHOLD_MINUTES = 10   # Report if nothing happening for 10 min
    
    def __init__(self, orchestrator):
        self.orchestrator = orchestrator
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._last_check = datetime.now()
        self._last_status_report = datetime.now()
        self._events: List[PulseEvent] = []
        self._callbacks: List[Callable] = []
        self._lock = threading.Lock()
        
        # Track what we've already reported to avoid spam
        self._reported_stuck: set = set()
        self._reported_errors: set = set()
        
    def register_callback(self, callback: Callable):
        """Register callback for pulse events"""
        self._callbacks.append(callback)
        
    def start(self):
        """Start the Manager's pulse"""
        if self._running:
            return
            
        self._running = True
        self._thread = threading.Thread(target=self._pulse_loop, daemon=True)
        self._thread.start()
        logger.info("Manager Pulse started")
        
        # Initial greeting
        self._add_event(PulseEvent(
            timestamp=datetime.now(),
            type="status_report",
            severity="info",
            message="👋 Manager is now actively monitoring the Workspace. I'll check on agents and missions every minute and report any issues."
        ))
        
    def stop(self):
        """Stop the pulse"""
        self._running = False
        if self._thread:
            self._thread.join(timeout=2.0)
        logger.info("Manager Pulse stopped")
        
    def _pulse_loop(self):
        """Main pulse loop"""
        last_health_check = 0
        last_mission_check = 0
        last_status_report = 0
        
        while self._running:
            current_time = time.time()
            
            # Health check every minute
            if current_time - last_health_check >= self.HEALTH_CHECK_INTERVAL:
                self._check_health()
                last_health_check = current_time
                
            # Mission check every 2 minutes
            if current_time - last_mission_check >= self.MISSION_CHECK_INTERVAL:
                self._check_missions()
                last_mission_check = current_time
                
            # Status report every 5 minutes
            if current_time - last_status_report >= self.STATUS_REPORT_INTERVAL:
                self._generate_status_report()
                last_status_report = current_time
                
            time.sleep(5)  # Small sleep to prevent busy-waiting
            
    def _check_health(self):
        """Check agent health and report issues"""
        health = self.orchestrator.health_monitor.get_health_summary()
        
        # Check for stuck agents
        for agent_id, agent_health in health.get('agents', {}).items():
            state = agent_health.get('state', '')
            name = agent_health.get('name', 'Unknown')
            
            if state == 'stuck' and agent_id not in self._reported_stuck:
                self._add_event(PulseEvent(
                    timestamp=datetime.now(),
                    type="agent_alert",
                    severity="warning",
                    message=f"⏱️ {name} has been working for {agent_health.get('time_in_state', 'unknown')} - may be stuck",
                    agent_id=agent_id,
                    suggested_action=f"Check on {name} or respawn if frozen"
                ))
                self._reported_stuck.add(agent_id)
                
            elif state == 'error' and agent_id not in self._reported_errors:
                self._add_event(PulseEvent(
                    timestamp=datetime.now(),
                    type="agent_alert",
                    severity="action_taken" if agent_health.get('consecutive_errors', 0) >= 3 else "warning",
                    message=f"🔴 {name} is in error state ({agent_health.get('consecutive_errors', 0)} errors)",
                    agent_id=agent_id,
                    suggested_action=f"Respawn {name} or check logs"
                ))
                self._reported_errors.add(agent_id)
                
            # Clear from reported if resolved
            elif state in ['idle', 'working'] and agent_id in self._reported_stuck:
                self._reported_stuck.discard(agent_id)
            elif state != 'error' and agent_id in self._reported_errors:
                self._reported_errors.discard(agent_id)
                
    def _check_missions(self):
        """Check mission progress and report"""
        missions = self.orchestrator.mission_manager.list_missions()
        active_missions = [m for m in missions if m.status.value == 'active']
        
        for mission in active_missions:
            # Calculate progress
            total = len(mission.tasks)
            completed = len([t for t in mission.tasks if t.status == 'completed'])
            in_progress = len([t for t in mission.tasks if t.status == 'in_progress'])
            
            # Check if mission is stuck (no progress for a while)
            # For now, just report current status
            if in_progress > 0 and completed == 0:
                # Mission started but nothing completed yet
                self._add_event(PulseEvent(
                    timestamp=datetime.now(),
                    type="mission_update",
                    severity="info",
                    message=f"📋 Mission '{mission.title}': {in_progress} task(s) in progress, {completed}/{total} completed",
                    mission_id=mission.id
                ))
                
    def _generate_status_report(self):
        """Generate periodic status report"""
        data = self.orchestrator.get_dashboard_data()
        health = data.get('health_summary', {})
        
        agents = data.get('agents', [])
        working = len([a for a in agents if a['status'] == 'working'])
        idle = len([a for a in agents if a['status'] == 'idle'])
        errors = health.get('error', 0)
        
        missions = data.get('missions', [])
        active_missions = len([m for m in missions if m['status'] == 'active'])
        
        # Only report if there's something interesting or every 3 reports
        if working > 0 or errors > 0 or active_missions > 0:
            msg_parts = ["📊 Workspace Status Update:"]
            msg_parts.append(f"• {len(agents)} agents ({working} working, {idle} idle)")
            
            if errors > 0:
                msg_parts.append(f"• ⚠️ {errors} agent(s) need attention")
            if active_missions > 0:
                msg_parts.append(f"• 📋 {active_missions} active mission(s)")
                
            # List who's working
            working_agents = [a for a in agents if a['status'] == 'working']
            if working_agents:
                msg_parts.append("\nCurrently working:")
                for a in working_agents:
                    task = a.get('current_task', 'unknown task')[:40]
                    msg_parts.append(f"  • {a['name']}: {task}...")
                    
            self._add_event(PulseEvent(
                timestamp=datetime.now(),
                type="status_report",
                severity="info",
                message="\n".join(msg_parts)
            ))
            
    def _add_event(self, event: PulseEvent):
        """Add event and notify callbacks"""
        with self._lock:
            self._events.append(event)
            # Keep last 100 events
            if len(self._events) > 100:
                self._events = self._events[-100:]
                
        # Notify callbacks
        for callback in self._callbacks:
            try:
                callback(event)
            except Exception as e:
                logger.error(f"Pulse callback error: {e}")
                
    def get_recent_events(self, limit: int = 20) -> List[PulseEvent]:
        """Get recent pulse events"""
        with self._lock:
            return list(self._events)[-limit:]
            
    def clear_events(self):
        """Clear all events"""
        with self._lock:
            self._events.clear()
            
    def get_stats(self) -> Dict:
        """Get pulse statistics"""
        with self._lock:
            return {
                'total_events': len(self._events),
                'running': self._running,
                'reported_stuck': len(self._reported_stuck),
                'reported_errors': len(self._reported_errors)
            }
